-- Provider pathway content. DRAFT: Spanish text needs native-speaker review, and every step with
-- verified_on = null must be checked against the official source before public launch.
-- verified_on is set only where the fact was confirmed against the linked source on that date.
insert into public.pathway_steps (permit_type, step_order, title_en, title_es, body_en, body_es, source_url, verified_on, reviewer) values
('registered', 1,
 'Check your deed restrictions first',
 'Primero revise las restricciones de su escritura',
 'Houston has no zoning, but many neighborhoods have deed restrictions. Some legally prohibit running a business from home. Check yours before spending money on licensing.',
 'Houston no tiene zonificación, pero muchos vecindarios tienen restricciones en la escritura. Algunas prohíben legalmente tener un negocio en casa. Revise las suyas antes de gastar dinero en la licencia.',
 'https://www.houstontx.gov/planning/Neighborhood/deed_restr.html', '2026-09-26', null),
('registered', 2,
 'Confirm a registered home fits your plans',
 'Confirme que un hogar registrado le conviene',
 'A registered child-care home can care for up to 6 unrelated children during school hours, plus up to 6 more school-age children after school. No more than 12 children total, including your own.',
 'Un hogar registrado de cuidado infantil puede cuidar hasta 6 niños que no son parientes durante el horario escolar, y hasta 6 niños más de edad escolar después de clases. No más de 12 niños en total, incluidos los suyos.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', '2026-09-26', null),
('registered', 3,
 'Read the minimum standards',
 'Lea los estándares mínimos',
 'Registered and licensed homes must follow Texas minimum standards in 26 TAC Chapter 747. These cover safety, supervision, training and your home''s space.',
 'Los hogares registrados y con licencia deben cumplir los estándares mínimos de Texas en el Capítulo 747 del 26 TAC. Cubren seguridad, supervisión, capacitación y el espacio de su casa.',
 'https://www.hhs.texas.gov/sites/default/files/documents/chapter-747-homes.pdf', '2026-09-26', null),
('registered', 4,
 'Complete the pre-application steps and apply',
 'Complete los pasos previos y presente su solicitud',
 'HHSC lists the orientation, forms and fees required to apply. Follow the official steps on the HHSC page.',
 'HHSC indica la orientación, los formularios y las cuotas necesarios para solicitar. Siga los pasos oficiales en la página de HHSC.',
 'https://www.hhs.texas.gov/providers/child-care-regulation/become-a-provider/become-a-child-care-home-provider', null, null),
('registered', 5,
 'Background checks for your household',
 'Verificación de antecedentes de su hogar',
 'Texas requires background checks for caregivers and certain household members. Check the official page for who needs one and how.',
 'Texas exige verificación de antecedentes para las cuidadoras y ciertos miembros del hogar. Consulte la página oficial para saber quién la necesita y cómo hacerla.',
 'https://www.hhs.texas.gov/providers/child-care-regulation/become-a-provider/become-a-child-care-home-provider', null, null),
('registered', 6,
 'Expect inspections',
 'Espere inspecciones',
 'Registered homes receive at least one unannounced monitoring inspection every one to two years.',
 'Los hogares registrados reciben al menos una inspección de supervisión sin previo aviso cada uno o dos años.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', '2026-09-26', null),
('registered', 7,
 'Accept childcare subsidies',
 'Acepte ayuda para cuidado infantil',
 'After you are approved, you can apply to serve families who receive Texas Workforce Commission Child Care Services scholarships. Check the current requirements, including Texas Rising Star.',
 'Después de ser aprobada, puede solicitar atender a familias que reciben becas de Child Care Services de la Comisión de la Fuerza Laboral de Texas. Consulte los requisitos actuales, incluido Texas Rising Star.',
 'https://www.twc.texas.gov/programs/child-care/for-providers', null, null),
('licensed_home', 1,
 'Confirm a licensed home fits your plans',
 'Confirme que un hogar con licencia le conviene',
 'A licensed child-care home is for about 7 to 12 children in your home, with more requirements than a registered home.',
 'Un hogar de cuidado infantil con licencia es para unos 7 a 12 niños en su casa, con más requisitos que un hogar registrado.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', null, null),
('licensed_home', 2,
 'Expect yearly inspections',
 'Espere inspecciones cada año',
 'Licensed homes receive at least one unannounced monitoring inspection per year.',
 'Los hogares con licencia reciben al menos una inspección de supervisión sin previo aviso cada año.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', '2026-09-26', null)
on conflict (permit_type, step_order) do nothing;
