-- Provider pathway content. DRAFT: Spanish text needs native-speaker review, and every step with
-- verified_on = null must be checked against the official source before public launch.
-- verified_on is set only where the fact was confirmed against the linked source on that date.
insert into public.pathway_steps (permit_type, step_order, title_en, title_es, body_en, body_es, source_url, verified_on, reviewer) values
('listed', 1,
 'Check your deed restrictions first',
 'Primero revise las restricciones de su escritura',
 'Houston has no zoning, but many neighborhoods have deed restrictions. Some legally prohibit running a business from home. Check yours before you start.',
 'Houston no tiene zonificación, pero muchos vecindarios tienen restricciones en la escritura. Algunas prohíben legalmente tener un negocio en casa. Revise las suyas antes de empezar.',
 'https://www.houstontx.gov/planning/Neighborhood/deed_restr.html', '2026-09-26', null),
('listed', 2,
 'Confirm a listed family home fits your plans',
 'Confirme que un hogar familiar en lista le conviene',
 'If you are paid to regularly care for 3 or fewer children who are not related to you, in your own home, Texas law says you must list your home with HHSC.',
 'Si le pagan por cuidar con regularidad a 3 niños o menos que no son sus parientes, en su propia casa, la ley de Texas dice que debe inscribir su hogar en la lista de HHSC.',
 'https://statutes.capitol.texas.gov/Docs/HR/htm/HR.42.htm', '2026-09-26', null),
('listed', 3,
 'List your home with HHSC',
 'Inscriba su hogar en HHSC',
 'HHSC explains how to list a family home, including forms and background checks. Follow the official steps.',
 'HHSC explica cómo inscribir un hogar familiar, incluidos los formularios y la verificación de antecedentes. Siga los pasos oficiales.',
 'https://www.hhs.texas.gov/providers/child-care-regulation/become-a-provider/become-a-child-care-home-provider', null, null),
('registered', 1,
 'Check your deed restrictions first',
 'Primero revise las restricciones de su escritura',
 'Houston has no zoning, but many neighborhoods have deed restrictions. Some legally prohibit running a business from home. Check yours before spending money on licensing.',
 'Houston no tiene zonificación, pero muchos vecindarios tienen restricciones en la escritura. Algunas prohíben legalmente tener un negocio en casa. Revise las suyas antes de gastar dinero en la licencia.',
 'https://www.houstontx.gov/planning/Neighborhood/deed_restr.html', '2026-09-26', null),
('registered', 2,
 'Confirm a registered home fits your plans',
 'Confirme que un hogar registrado le conviene',
 'Texas law says a home caring for 4 or more unrelated children must register. A registered home can care for up to 6 unrelated children under 14, plus up to 6 more elementary school children after school, with no more than 12 children in total, including your own.',
 'La ley de Texas dice que un hogar que cuida a 4 o más niños que no son parientes debe registrarse. Un hogar registrado puede cuidar hasta 6 niños menores de 14 años que no son parientes, más hasta 6 niños de primaria después de clases, con un máximo de 12 niños en total, incluidos los suyos.',
 'https://statutes.capitol.texas.gov/Docs/HR/htm/HR.42.htm', '2026-09-26', null),
('registered', 3,
 'Read the minimum standards',
 'Lea los estándares mínimos',
 'Registered and licensed homes must follow Texas minimum standards in 26 TAC Chapter 747. These cover safety, supervision, training and your home''s space.',
 'Los hogares registrados y con licencia deben cumplir los estándares mínimos de Texas en el Capítulo 747 del 26 TAC. Cubren seguridad, supervisión, capacitación y el espacio de su casa.',
 'https://www.hhs.texas.gov/sites/default/files/documents/chapter-747-homes.pdf', '2026-09-26', null),
('registered', 4,
 'Complete the pre-application steps and apply',
 'Complete los pasos previos y presente su solicitud',
 'HHSC lists the orientation, forms and fees required to apply. Follow the official steps on the HHSC page.',
 'HHSC indica la orientación, los formularios y las cuotas necesarios para solicitar. Siga los pasos oficiales en la página de HHSC.',
 'https://www.hhs.texas.gov/providers/child-care-regulation/become-a-provider/become-a-child-care-home-provider', null, null),
('registered', 5,
 'Background checks for your household',
 'Verificación de antecedentes de su hogar',
 'Texas requires background checks for caregivers and certain household members. Check the official page for who needs one and how.',
 'Texas exige verificación de antecedentes para las cuidadoras y ciertos miembros del hogar. Consulte la página oficial para saber quién la necesita y cómo hacerla.',
 'https://www.hhs.texas.gov/providers/child-care-regulation/become-a-provider/become-a-child-care-home-provider', null, null),
('registered', 6,
 'Expect inspections',
 'Espere inspecciones',
 'Registered homes receive at least one unannounced monitoring inspection every one to two years.',
 'Los hogares registrados reciben al menos una inspección de supervisión sin previo aviso cada uno o dos años.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', '2026-09-26', null),
('registered', 7,
 'Accept childcare subsidies',
 'Acepte ayuda para cuidado infantil',
 'Licensed and registered providers can be paid to care for children who receive Texas Workforce Commission Child Care Services scholarships. After you are approved, contact Texas Child Care Solutions or your local Workforce Solutions office to enroll.',
 'Los proveedores con licencia y registrados pueden recibir pago por cuidar a niños con becas de Child Care Services de la Comisión de la Fuerza Laboral de Texas. Después de ser aprobada, comuníquese con Texas Child Care Solutions o con su oficina local de Workforce Solutions para inscribirse.',
 'https://www.twc.texas.gov/programs/child-care/for-providers', '2026-09-26', null),
('licensed_home', 1,
 'Confirm a licensed home fits your plans',
 'Confirme que un hogar con licencia le conviene',
 'Caring for 7 or more children in your own home makes it a group day-care home under Texas law, which needs a license (HHSC calls it a licensed child-care home). HHSC rules set the maximum number of children; check the official page.',
 'Cuidar a 7 o más niños en su propia casa la convierte en un hogar de cuidado grupal según la ley de Texas, y necesita licencia (HHSC lo llama hogar de cuidado infantil con licencia). Las reglas de HHSC fijan el número máximo de niños; consulte la página oficial.',
 'https://statutes.capitol.texas.gov/Docs/HR/htm/HR.42.htm', '2026-09-26', null),
('licensed_home', 2,
 'Expect yearly inspections',
 'Espere inspecciones cada año',
 'Licensed homes receive at least one unannounced monitoring inspection per year.',
 'Los hogares con licencia reciben al menos una inspección de supervisión sin previo aviso cada año.',
 'https://www.hhs.texas.gov/sites/default/files/documents/doing-business-with-hhs/provider-portal/protective-services/ccl/licensed-registered-listed-family-child-care-home.pdf', '2026-09-26', null)
on conflict (permit_type, step_order) do nothing;
